include:
  - cider-ci/task-components/asdf-nodejs.yml

scripts:

  my-service-run:
    start_when:
      nodejs is installed:
        script_key: my-nodejs-asdf-install
      uberjar has been built:
        script_key: my-build-uberjar
      database has been created:
        script_key: create-database
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_MY_DIR
      mkdir -p $LEIHS_MY_DIR/tmp
      unset PGPORT
      unset PGUSER
      PGPORT=${PG10PORT} PGUSER=${PG10USER} HTTP_PORT=${LEIHS_MY_HTTP_PORT} \
        java \
          -jar target/leihs-my.jar \
          run --pid-file tmp/service.pid

  my-service-is-running:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      until curl --fail -I \
        -H 'Accept: application/json' \
        "http://localhost:${LEIHS_MY_HTTP_PORT}/my/status";
        do sleep 1;
      done
    start_when:
      run server is executing:
        script_key: my-service-run
        states: [executing]

  test:
    start_when:
      my service is running:
        script_key: my-service-is-running

  my-service-shutdown:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_MY_DIR
      export PID=$(cat tmp/service.pid)
      kill $PID
      tail --pid=$PID -f /dev/null
    start_when:
      test is terminal:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]

  delete-database:
    start_when:
       my-service-shutdown is in termial state:
        script_key: my-service-shutdown
        states: [aborted, defective, passed, failed, skipped]
