name: LEIHS/leihs/my
windows:
  2:
    name: server-dev
    command: |
      ./bin/dev-run-backend
  3:
    name: front-dev
    command: |
      bin/dev-run-frontend
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  7:
    name: test
    command: |
      export TEST_AUTH_SYSTEM_PORT=3245
      export RAILS_ENV=test
  8:
    name: shared-clj
    command: |
      cd shared-clj
  9:
    name: auth-sys
    command: |
      export TEST_AUTH_SYSTEM_PORT=3245
      bundle exec ruby bin/test-auth-system.rb -p ${TEST_AUTH_SYSTEM_PORT}
