name: LEIHS/v5/my
windows:
  2:
    name: app
    command: |
      export LEIHS_MY_HTTP_BASE_URL=http://localhost:3240
      lein do clean, repl
    post_command_send_keys: |
      (-main "run")
  3:
    name: figwheel
    command: |
      ./scripts/prepare-shared-ui.sh && \
      lein figwheel
  5:
    name: psql
    command: |
      psql -d leihs
  6:
    name: db
    command: |
      cd database
  7:
    name: test
    command: |
      export LEIHS_MY_HTTP_BASE_URL=http://localhost:3240
      export TEST_AUTH_SYSTEM_PORT=3245
      export RAILS_ENV=test
  8:
    name: log
    command: |
      mkdir -p log && echo " " > log/debug.log && tail -f log/debug.log
  9: 
    name: auth-sys
    command: |
      export TEST_AUTH_SYSTEM_PORT=3245
      bundle exec ruby bin/test-auth-system.rb -p ${TEST_AUTH_SYSTEM_PORT}
