jobs:

  my-build-uberjar:
    name: Build my uberjar
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      task_defaults:
        environment_variables:
          LEIHS_MY_DIR: '{{CIDER_CI_WORKING_DIR}}'
      tasks:
        my-build-uberjar:
          { include: cider-ci/uberjar_task-component.yml }

  specs:
    name: Run specs
    depends_on: &SPEC_DEPENDENTS
      uberjar passed:
        type: job
        job_key: my-build-uberjar
        states: [passed]
    run_when: *SPEC_DEPENDENTS
    context: { include: cider-ci/specs_job-context.yml }

  good-to-merge:
    name: ⚑ Good To Merge
    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      Status of this job is **used by github's "branch protection"**!
    include: cider-ci/good-to-merge_job-context.yml

