eval_gemfile 'database/Gemfile'

gem 'capybara', '~> 3.8'
gem 'faraday'
gem 'faraday_middleware'
gem 'haml'
gem 'jwt'
gem 'geckodriver-helper'
gem 'puma'
gem 'rexml'
gem 'selenium-webdriver', '~> 3.14'
gem 'sinatra'
